# vim:tw=0:ts=4:sw=4:et:norl
# Author: Landon Bouma <https://tallybark.com/>
# Project: https://github.com/doblabs/tempita-hotoffthehamster#🦓
# License: MIT

EAPP_MAKEFILE_PYDOCSTYLE_DISABLE ?= true

